
###
GET http://121.169.215.212:3000/sum HTTP/1.1

###
POST http://localhost:3000/add HTTP/1.1
content-type: application/json

{
    "input": 2
}

###
GET http://localhost:3000/sum HTTP/1.1

###

GET http://localhost:3000/reset HTTP/1.1

###
GET http://localhost:3000/sum HTTP/1.1

